<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<!-- ÉP CÀI ĐẶT THƯ VIỆN GIAO DIỆN TERMINAL V1.19 -->
	<ItemGroup>
		<PackageReference Include="Terminal.Gui" Version="1.19.0" />
	</ItemGroup>

	<!-- LIÊN KẾT ĐÚNG CHUẨN 3-TIER -->
	<ItemGroup>
		<ProjectReference Include="..\MISUP.BLL\MISUP.BLL.csproj" />
		<ProjectReference Include="..\MISUP.Models\MISUP.Models.csproj" />
	</ItemGroup>

</Project>